# Generated by Django 5.1.4 on 2025-02-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('categoria', models.CharField(choices=[('Servicio', 'Servicio'), ('Instalaciones', 'Instalaciones'), ('Comida', 'Comida')], max_length=20)),
                ('sugerencia', models.TextField(max_length=500)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
