# Generated by Django 5.1.4 on 2025-02-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbre', '0002_sugerencia_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sugerencia',
            name='fecha_envio',
        ),
        migrations.RemoveField(
            model_name='sugerencia',
            name='mensaje',
        ),
        migrations.AlterField(
            model_name='sugerencia',
            name='categoria',
            field=models.CharField(choices=[('Servicio', 'Servicio'), ('Instalaciones', 'Instalaciones'), ('Comida', 'Comida')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sugerencia',
            name='sugerencia',
            field=models.TextField(),
        ),
    ]
