# Generated by Django 5.1.4 on 2025-02-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbre', '0004_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activation_token',
            field=models.CharField(default='c70ae54d91824f4296702a71e9c72654', max_length=64, unique=True),
        ),
    ]
