# Generated by Django 5.1.4 on 2025-02-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbre', '0005_usuario_activation_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default='defaultpassword', max_length=128),
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='activation_token',
            field=models.CharField(default='1f34fe06ad1d4fc78cab1a055d3b1449', max_length=64, unique=True),
        ),
    ]
