# Generated by Django 5.1.4 on 2025-02-10 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbre', '0006_remove_usuario_email_remove_usuario_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabaña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='activation_token',
            field=models.CharField(default='7d509dc498d74b1d84be5e3751df32b1', max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(unique=True)),
                ('numero_personas', models.PositiveIntegerField()),
                ('telefono', models.CharField(max_length=15)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=10)),
                ('cabaña', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kumbre.cabaña')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
