# Generated by Django 5.1.4 on 2025-02-10 05:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbre', '0007_cabaña_alter_usuario_activation_token_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabaña',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='activation_token',
            field=models.CharField(default='36ed4039067641598a2e41a0cebe7f22', max_length=64, unique=True),
        ),
    ]
