# Generated by Django 5.1.4 on 2025-02-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbre', '0009_alter_reserva_fecha_reserva_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='cabaña',
            new_name='cabana',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='activation_token',
            field=models.CharField(default='0d6c1df0a8a9462bac0937f619a94661', max_length=64, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('cabana', 'fecha_reserva')},
        ),
    ]
