# Generated by Django 5.1.4 on 2025-02-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbre', '0010_rename_cabaña_reserva_cabana_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cabaña',
            new_name='Cabana',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='activation_token',
            field=models.CharField(default='7bf05b19c37442e8b55024773805b855', max_length=64, unique=True),
        ),
    ]
