# Generated by Django 5.1.4 on 2025-02-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbre', '0012_alter_reserva_usuario_alter_usuario_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='activation_token',
            field=models.CharField(default='665018970a2046ab90c785fe236bd7db', max_length=64, unique=True),
        ),
    ]
