# Generated by Django 5.1.6 on 2025-02-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbre', '0013_alter_usuario_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='activation_token',
            field=models.CharField(default='43bf91ee73c24fe5abfcaae8fed6c591', max_length=64, unique=True),
        ),
    ]
