# Generated by Django 5.1.6 on 2025-02-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kumbre', '0015_remove_usuario_activation_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sugerencia',
            old_name='nombre',
            new_name='username',
        ),
    ]
