# Generated by Django 5.1.6 on 2025-03-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbre', '0017_cabana_descripcion_cabana_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_reserva',
            new_name='fecha',
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reserva',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cabana',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cabana',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='created_at',
        ),
    ]
