# Generated by Django 5.1.6 on 2025-03-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbre', '0019_alter_reserva_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='confirmada',
            field=models.BooleanField(default=False),
        ),
    ]
