# Generated by Django 5.1.6 on 2025-03-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbre', '0021_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
