# Generated by Django 5.1.4 on 2025-04-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbre', '0026_festivo_preciocabana'),
    ]

    operations = [
        migrations.AddField(
            model_name='preciocabana',
            name='precio_persona_adicional_entre_semana',
            field=models.DecimalField(decimal_places=2, default=60000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='preciocabana',
            name='precio_persona_adicional_finde_festivo',
            field=models.DecimalField(decimal_places=2, default=80000.0, max_digits=10),
        ),
    ]
