# Generated by Django 5.1.4 on 2025-04-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbre', '0028_reserva_personas_adicionales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='horario_comida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
