# Generated by Django 5.1.4 on 2025-04-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbre', '0029_compra_horario_comida'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='comprobante_pago',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes_pago/'),
        ),
    ]
