# Generated by Django 5.1.4 on 2025-05-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbre', '0030_compra_comprobante_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
